MegaSa1nt/GMDprivateServer

dashboard/login/login.php
Fixed the broken redirect on the login page, although since I've never coded PHP I probably didn't use the absolute best method.
also yes i tested it
=> Fix broken redirect after login

config/dailyChests.php
=> Add 2.2 shards to daily chests

incl/lib/mainLib.php
for whatever reason when there is a role but the user doesnt have an assignment it will return true
=> fix mod perms

dashboard/incl/lang/localeEN.php, dashboard/incl/lang/localeES.php, dashboard/incl/lang/localeFR.php, dashboard/incl/lang/localeRU.php, dashboard/incl/lang/localeTR.php, dashboard/incl/lang/localeUA.php, dashboard/profile/index.php
=> Allow changing timezones from profile settings

README.md, config/security.php, incl/lib/connection.php, incl/lib/ipCheck.php
---------
Full changelog:
- Add the "blockCommonVPNs" option in config/security.php
- Add credits to the VPN list in the README.md file
- Add a function to check if the user uses a VPN in the incl/lib/ipCheck.php file
=> Block Common VPNs

dashboard/api/searchLevel.php
Adds the file searchLevel.php file in dashboard/api, which returns a bunch of informations about a level in a nice JSON format
=> Search Level API

dashboard/clan/index.php, dashboard/incl/dashboardLib.php
Now in clan profile there are stats of every clan member combined
=> Add total clan stats

config/dashboard.php, incl/scores/getGJScores.php
Originally made by [zkayns](https://github.com/zkayns) ([see here](https://github.com/Cvolton/GMDprivateServer/pull/1006))
=> Sakujes toggle

dashboard/clans/index.php
=> Order clans by member count

dashboard/profile/index.php
For the icon kit you could also add color 3 regarding the glow!
=> Small icon kit update: add color 3 & glow!

config/discord.php, incl/lib/mainLib.php
You can set roles which will be mentioned while sending notifications for various events.
=> Send additional text outside of webhook embeds (able to mention roles/users)

tools/index.php
zero point in not just having it... you know redirect?
=> remove useless tools page link

dashboard/profile/index.php, incl/profiles/getGJUserInfo.php, incl/profiles/updateGJAccSettings.php
may cause issues, only tested youtube
you can do @ for youtube handles in the dashboard, or using character filter in game
=> filter socials

config/reuploadAcc.php, dashboard/levels/levelReupload.php
pretty much, config/reuploadAcc.php did nothing so I thought I would make it optional for using the dashboard logged in users account or the reupload account
=> automatic reupload user & account ids option

incl/levels/getGJLevels.php, incl/lib/commands.php, incl/lib/mainLib.php
Adds featured score and order levels by their featured score in the Featured tab
----------
Changelog:
- Order levels in the Featured tab by their featured score instead of the data when they were rated (`incl/levels/getLevels.php`)
- Add featured score support with commands (`incl/lib/commands.php`)
- Rewrite the featureLevel function to optimize it with featured scores (`incl/lib/mainLib.php`)
=> Featured Score

accounts/registerGJAccount.php, dashboard/login/register.php
Check for spaces in a username and return -4 if it finds one (registerGJAccount.php)
=> Check spaces in username

config/discord.php, incl/lib/mainLib.php
Adds a setting in `config/discord.php` to customize the URL where icons are stored for Discord webhooks
=> Custom difficulty icons URL

incl/comments/uploadGJComment.php
As the name suggests :trollface:
=> Check for invalid percentage in comments before uploading

config/misc.php, incl/levels/getGJLevels.php
This allows to have the vanilla GD view of levels, where you can see (im)compatible levels
=> Show all levels ("aka NA levels")

incl/lib/mainLib.php
Very small addition for those who want to integrate the Geometry Dash songs also present in other games into their server. For PC you have to add them manually on `\Resources`, however on Android you have to add them on `\assets`!
=> Adds SubZero & Explorers songs to the function

config/misc.php, incl/lib/connection.php
=> Add settings to set minimum and maximum Game/Binary Versions

incl/lib/mainLib.php
@MegaSa1nt as soon as you finish developing the GD clients for 2.206, especially to add NCS songs into the game, add this for gauntlets too. Luckily there are no new server-side features to add, at least for now.
=> Gauntlets update 2.206

incl/lib/exploitPatch.php
To avoid breaking URLs and some searches with the "_" character
Note: Removed delimiters from old PR.
=> Adding the "_" character to ruchar pattern

incl/lib/exploitPatch.php
Some servers use this symbol in their URLs such as Discord CDN or Firebase Hosting CDN.
I forgot to add it, sorry
=> Adding "&" to rucharclean

README.md, incl/lib/ipCheck.php, incl/lib/mainLib.php
Add Cloudflare IPV6 ranges support.
Unfortunately was not able to test this myself.
=> Cloudflare IPV6 support

config/misc.php, tools/cron/fixcps.php
=> Fix unlisted levels being counted in the creator points calculation

incl/levelpacks/getGJLevelLists.php
I applied the same function present on getGJLevels.php also for lists
=> See unlisted lists in "My online lists" page

incl/lib/mainLib.php
Fix another bug related to 2.0, where unregistered account can't upload level to the server.
=> Unregistered users on new versions fix

incl/relationships/blockGJUser.php
Credits to Fenix688 for the SQL commands (#197)
=> Unfriend blocked users

dashboard/incl/dashboardLib.php, dashboard/incl/lang/localeIT.php, dashboard/stats/accountsList.php, dashboard/stats/listsTable.php, dashboard/stats/listsTableMod.php, dashboard/stats/listsTableYour.php, dashboard/stats/modActionsList.php, dashboard/stats/modList.php, dashboard/stats/top24h.php
Avatars with "value=0" will no longer be displayed in mini format and those with values ​​equal than 0, if there is someone who does not update the profile and display their icons, will always be returned as 1 to avoid displaying mini icons.
Then, a small addition to make the comments section very similar to that of GD, I also added colored text only for those who have taken on a special role in the game, such as mods.
Instead of "color management" I could also very well add getAccountCommentColor and save time. But I preferred to do this to leave the font color of the comment as default rather than having it come out white (which on getAccountCommentColor is 255,255,255) if the role is not found.
=> Updated Italian language + corrections

config/webhooks/lang/PL.php, dashboard/incl/lang/localePL.php
I saw a few things being added, so I translated them. Changed few more words to make it sound better
=> pl translation update

dashboard/incl/dashboardLib.php, dashboard/incl/lang/localePL.php
just realised that 1 thing doesn't really fit so fixed + my name update
=> another small pl update

README.md, api/v1/levels/gmd.php, api/v1/levels/lastFeaturedID.php, api/v1/levels/rateDemon.php, api/v1/levels/sends.php, api/v1/misc/cron.php
updated the readability of the `README.md` file and fixed the paths to the files in the `api` folder :)
=> Update README file and fix API paths

incl/levelpacks/getGJLevelLists.php, incl/lib/commands.php, incl/lib/mainLib.php
=> small bugfixes & unsuggest command logic
